version: "4.67.0"

services:

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: emr-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - CLIENT_ORIGIN=http://localhost:5173

      - MONGO_URI=${MONGO_URI}

      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_RESET_SECRET=${JWT_RESET_SECRET}

      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}

      - RAZORPAY_MODE=${RAZORPAY_MODE}
      - RAZORPAY_KEY_ID_TEST=${RAZORPAY_KEY_ID_TEST}
      - RAZORPAY_KEY_SECRET_TEST=${RAZORPAY_KEY_SECRET_TEST}

      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

    depends_on:
      - mongo
    restart: unless-stopped


  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: emr-client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped


  mongo:
    image: mongo:7
    container_name: emr-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: